# Generated by Django 5.2 on 2025-04-14 11:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200, unique=True)),
                ('agent_id', models.CharField(blank=True, max_length=25, null=True)),
                ('agent_users_idx_or_id', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_email', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_address1', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_address2', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_postal_code', models.CharField(blank=True, max_length=25, null=True)),
                ('agent_location', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_phone_1', models.CharField(blank=True, max_length=25, null=True)),
                ('agent_phone_2', models.CharField(blank=True, max_length=25, null=True)),
                ('agent_phone_3', models.CharField(blank=True, max_length=25, null=True)),
                ('agent_about', models.TextField(blank=True, null=True)),
                ('agent_years_in_industry', models.IntegerField(blank=True, null=True)),
                ('agent_specialties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('agent_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('agent_is_active', models.BooleanField(default=False)),
                ('agent_is_team_lead', models.BooleanField(default=False)),
                ('agent_is_top_agent', models.BooleanField(default=False)),
                ('agent_is_verify_agent_tel', models.BooleanField(default=False)),
                ('agent_is_awards', models.BooleanField(default=False)),
                ('agent_awards_year', models.CharField(blank=True, max_length=25, null=True)),
                ('agent_review_excerpt', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_review_excerpt_date', models.DateTimeField(blank=True, null=True)),
                ('agent_review_link', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_num_total_reviews', models.IntegerField(blank=True, null=True)),
                ('agent_review_star_rating', models.FloatField(blank=True, null=True)),
                ('agent_profile_url', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_website_url', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_facebook_url', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_linkedIn_url', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_x_url', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_instagram_url', models.CharField(blank=True, max_length=500, null=True)),
                ('licenses_number', models.CharField(blank=True, max_length=50, null=True)),
                ('licenses_state', models.CharField(blank=True, max_length=25, null=True)),
                ('licenses_status', models.CharField(blank=True, max_length=25, null=True)),
                ('licenses_original_status', models.CharField(blank=True, max_length=25, null=True)),
                ('licenses_type', models.CharField(blank=True, max_length=25, null=True)),
                ('licences_expiration_date', models.CharField(blank=True, max_length=25, null=True)),
                ('sale_count_all_time', models.IntegerField(blank=True, null=True)),
                ('sale_count_last_year', models.IntegerField(blank=True, null=True)),
                ('sale_price_range_three_year_min', models.IntegerField(blank=True, null=True)),
                ('sale_price_range_three_year_max', models.IntegerField(blank=True, null=True)),
                ('json_full', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agent',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ad_guarantee', models.BooleanField(default=False)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('parent_logo_url', models.URLField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_id', models.CharField(default='0000000', max_length=255, unique=True)),
                ('json_field', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='New', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
