# Generated by Django 5.2 on 2025-04-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_agent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(blank=True, default='New', max_length=50, null=True),
        ),
    ]
