# Generated by Django 5.2 on 2025-04-14 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_agent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
